# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)
  displayName: 'dotnet publish $(buildConfiguration) to Staging Directory'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.artifactstagingdirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/hansmond-da.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/hansmond-da.zip'
    ArtifactName: 'hansmond-da'
    publishLocation: 'Container'
